export type IDialog =
  | 'config'
  | 'copyFile'
  | 'copyFolder'
  | 'create'
  | 'createFolder'
  | 'deleteFile'
  | 'deleteFolder'
  | 'fetchFile'
  | 'indexFiles'
  | 'moveFile'
  | 'moveFolder'
