export type IDialog =
  | 'addEmptyFolder'
  | 'addRemoteDataset'
  | 'addRemoteFile'
  | 'adjustFile'
  | 'config'
  | 'copyFile'
  | 'copyFolder'
  | 'create'
  | 'deleteFile'
  | 'deleteFolder'
  | 'indexFiles'
  | 'moveFile'
  | 'moveFolder'
