import os
import platform
import PyInstaller.__main__
import subprocess
import sys


def run(cmd: list[str], cwd: str = "."):
    """Run a subprocess command."""
    subprocess.run(cmd, check=True, cwd=cwd)


def docs():
    """Build the documentation and run a local server."""
    run(["make", "html"], cwd="docs")
    run(["python", "-m", "http.server", "-d", "build/html"], cwd="docs")


def update_translations():
    """Generate/update .ts files from the source code."""
    run(["pyside6-lupdate", "-extensions", "py", "-recursive", "ode", "-ts", "ode/assets/translations/de.ts", "-target-language", "de_DE"])
    run(["pyside6-lupdate", "-extensions", "py", "-recursive", "ode", "-ts", "ode/assets/translations/es.ts", "-target-language", "es_ES"])
    run(["pyside6-lupdate", "-extensions", "py", "-recursive", "ode", "-ts", "ode/assets/translations/fr.ts", "-target-language", "fr_FR"])
    run(["pyside6-lupdate", "-extensions", "py", "-recursive", "ode", "-ts", "ode/assets/translations/pt.ts", "-target-language", "pt_PT"])
    run(["pyside6-lupdate", "-extensions", "py", "-recursive", "ode", "-ts", "ode/assets/translations/it.ts", "-target-language", "it_IT"])


def compile_translations():
    """Compile .ts to .qm files."""
    run(["pyside6-lrelease", "ode/assets/translations/de.ts", "-qm", "ode/assets/translations/de.qm"])
    run(["pyside6-lrelease", "ode/assets/translations/es.ts", "-qm", "ode/assets/translations/es.qm"])
    run(["pyside6-lrelease", "ode/assets/translations/fr.ts", "-qm", "ode/assets/translations/fr.qm"])
    run(["pyside6-lrelease", "ode/assets/translations/pt.ts", "-qm", "ode/assets/translations/pt.qm"])
    run(["pyside6-lrelease", "ode/assets/translations/it.ts", "-qm", "ode/assets/translations/it.qm"])


def build_application():
    """Build an executable file for the Application."""
    system = platform.system()

    # Linux Defaults
    icon_path = "packaging/linux/icon.svg"
    app_name = "opendataeditor"

    if system == "Darwin":  # macOS
        icon_path = "packaging/macos/icon.icns"
        app_name = "OpenDataEditor"
    elif system == "Windows":
        icon_path = "packaging/windows/icon.ico"
        app_name = "opendataeditor"

    print("Creating executable file for Open Data Editor")

    params = [
        "src/ode/main.py",
        "--windowed",  # Required for Windows install to not open a console.
        "--collect-all",
        "frictionless",  # Frictionless depends on data files
        "--collect-all",
        "ode",  # Collect all assets from Open Data Editor
        "--collect-all",
        "llama_cpp",  # Collect all assets from llama_cpp
        "--collect-all",
        "numpy",  # Collect all assets from numpy (llama_cpp dependency)
        "--log-level",
        "WARN",
        "--name",
        app_name,
        "--noconfirm",
        "--icon",
        icon_path,
    ]

    if system == "Darwin":
        params.extend(["--osx-bundle-identifier", "org.okfn.opendataeditor"])

    if system == "Windows":
        # llama_cpp depends on vcomp140.dll and it is not properly collected by PyInstaller as it
        # is a dependency of shiboken6 as well. This library is only present in Windows if C++ Redistributable
        # is installed which might not be the case for all of our users.
        params.extend(["--add-binary", "C:\\Windows\\system32\\vcomp140.dll:."])

    # Allow calling `python build.py build` with extra arguments
    # e.g. when building AppImage `python build.py build --onefile --name "opendataeditor-X.Y.Z.AppImage"`
    cli_args =  sys.argv[2:]
    if cli_args:
        params.extend(cli_args)

    PyInstaller.__main__.run(params)

    # Clean the spec file generated by PyInstaller
    if os.path.exists(f"{app_name}.spec"):
        os.remove(f"{app_name}.spec")


def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python build.py update-translations")
        print("  python build.py compile-translations")
        print("  python build.py build")
        print("  python build.py docs")
        sys.exit(1)

    command = sys.argv[1].lower()

    if command == "update-translations":
        update_translations()
    elif command == "compile-translations":
        compile_translations()
    elif command == "build":
        build_application()
    elif command == "docs":
        docs()
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)


if __name__ == "__main__":
    main()
