export type IDialog =
  | 'copyFile'
  | 'copyFolder'
  | 'createFile'
  | 'createFolder'
  | 'createDataset'
  | 'createArticle'
  | 'createChart'
  | 'createScript'
  | 'createView'
  | 'deleteFile'
  | 'deleteFolder'
  | 'fetchFile'
  | 'indexFiles'
  | 'moveFile'
  | 'moveFolder'
