export type IDialog =
  | 'addEmptyFolder'
  | 'addRemoteFile'
  | 'adjustFile'
  | 'config'
  | 'configProject'
  | 'copyFile'
  | 'copyFolder'
  | 'create'
  | 'deleteFilesFolders'
  | 'indexFiles'
  | 'moveFile'
  | 'moveFolder'
  | 'start'
